-- DROP SCHEMA seguranca;

CREATE SCHEMA IF NOT EXISTS seguranca;
SET search_path TO seguranca;


-- seguranca.consentimento definition

-- Drop table

-- DROP TABLE seguranca.consentimento;

CREATE TABLE seguranca.consentimento (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	organizacao_id uuid NOT NULL,
	keycloak_sub uuid NOT NULL,
	tipo_consentimento varchar(64) NOT NULL,
	status varchar(32) DEFAULT 'ATIVO'::character varying NOT NULL,
    criado_por      UUID NOT NULL,
    criado_em       TIMESTAMPTZ NOT NULL,
    atualizado_por  UUID NOT NULL,
    atualizado_em   TIMESTAMPTZ NOT NULL,
    versao INTEGER DEFAULT 0 NOT NULL
);


-- seguranca.dispositivo definition

-- Drop table

-- DROP TABLE seguranca.dispositivo;

CREATE TABLE seguranca.dispositivo (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	identificador_dispositivo varchar(128) NOT NULL,
	keycloak_sub uuid NULL,
	nivel_confianca varchar(16) NOT NULL,
	plataforma varchar(32) NULL,
    criado_por      UUID NOT NULL,
    criado_em       TIMESTAMPTZ NOT NULL,
    atualizado_por  UUID NOT NULL,
    atualizado_em   TIMESTAMPTZ NOT NULL,
    versao INTEGER DEFAULT 0 NOT NULL,
	CONSTRAINT dispositivo_identificador_dispositivo_key_1 UNIQUE (identificador_dispositivo)
);


-- seguranca.excecao_permissao_usuario definition

-- Drop table

-- DROP TABLE seguranca.excecao_permissao_usuario;

CREATE TABLE seguranca.excecao_permissao_usuario (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	organizacao_id uuid NOT NULL,
	keycloak_sub uuid NOT NULL,
	recurso varchar(128) NOT NULL,
	escopo varchar(64) NOT NULL,
	condicao_json jsonb NULL,
    criado_por      UUID NOT NULL,
    criado_em       TIMESTAMPTZ NOT NULL,
    atualizado_por  UUID NOT NULL,
    atualizado_em   TIMESTAMPTZ NOT NULL,
    versao INTEGER DEFAULT 0 NOT NULL
);
CREATE INDEX idx_permissao_org_usuario_1 ON seguranca.excecao_permissao_usuario USING btree (organizacao_id, keycloak_sub);


-- seguranca.log_auditoria definition

-- Drop table

-- DROP TABLE seguranca.log_auditoria;

CREATE TABLE seguranca.log_auditoria (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	organizacao_id uuid NULL,
	acao varchar(128) NOT NULL,
	tipo_entidade varchar(64) NULL,
	entidade_id varchar(64) NULL,
	decisao varchar(16) NULL,
	metadados jsonb NULL,
    criado_por      UUID NOT NULL,
    criado_em       TIMESTAMPTZ NOT NULL
);
CREATE INDEX idx_auditoria_org_tempo_1 ON seguranca.log_auditoria USING btree (organizacao_id, criado_em);


-- seguranca.perfil_biometrico definition

-- Drop table

-- DROP TABLE seguranca.perfil_biometrico;

CREATE TABLE seguranca.perfil_biometrico (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	keycloak_sub uuid NOT NULL,
	modelo_biometrico bytea NOT NULL,
	versao_modelo varchar(32) NOT NULL,
    criado_por      UUID NOT NULL,
    criado_em       TIMESTAMPTZ NOT NULL,
    atualizado_por  UUID NOT NULL,
    atualizado_em   TIMESTAMPTZ NOT NULL,
    versao INTEGER DEFAULT 0 NOT NULL
);


-- seguranca.relacionamento definition

-- Drop table

-- DROP TABLE seguranca.relacionamento;

CREATE TABLE seguranca.relacionamento (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	organizacao_id uuid NOT NULL,
	sujeito_id uuid NOT NULL,
	objeto_id varchar(64) NOT NULL,
	tipo_relacionamento varchar(64) NOT NULL,
	inicio_validade TIMESTAMPTZ NULL,
	fim_validade TIMESTAMPTZ NULL,
    criado_por      UUID NOT NULL,
    criado_em       TIMESTAMPTZ NOT NULL,
    atualizado_por  UUID NOT NULL,
    atualizado_em   TIMESTAMPTZ NOT NULL,
    versao INTEGER DEFAULT 0 NOT NULL
);
CREATE INDEX idx_relacionamento_org_objeto_1 ON seguranca.relacionamento USING btree (organizacao_id, objeto_id);
CREATE INDEX idx_relacionamento_org_sujeito_1 ON seguranca.relacionamento USING btree (organizacao_id, sujeito_id);


-- seguranca.identidade_acesso definition

-- Drop table

-- DROP TABLE seguranca.identidade_acesso;

CREATE TABLE seguranca.identidade_acesso (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pessoa_id BIGINT NOT NULL,
    keycloak_sub uuid NOT NULL,
    provedor varchar(32) DEFAULT 'keycloak' NOT NULL,
    criado_por      UUID NOT NULL,
    criado_em       TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_identidade_pessoa FOREIGN KEY (pessoa_id) REFERENCES pessoa.pessoa(id) ON DELETE CASCADE,
    CONSTRAINT uq_identidade_sub UNIQUE (keycloak_sub)
);

-- Índice para otimizar as buscas no momento do login pelo interceptador de segurança
CREATE INDEX idx_identidade_acesso_sub ON seguranca.identidade_acesso USING btree (keycloak_sub);

-- ==============================================================================
-- BLINDAGEM DE TABELAS IMUTÁVEIS (Append-Only)
-- ==============================================================================

-- 1. Cria a função de bloqueio (usando OR REPLACE para ser idempotente)
CREATE OR REPLACE FUNCTION seguranca.proc_bloquear_mutacao()
RETURNS TRIGGER AS $$
BEGIN
    RAISE EXCEPTION 'VIOLAÇÃO DE SEGURANÇA: A tabela % é imutável. Operações de UPDATE ou DELETE são estritamente proibidas.', TG_TABLE_NAME;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

-- 2. Aplica a Trigger nas tabelas
DROP TRIGGER IF EXISTS trg_auditoria_imutavel ON seguranca.log_auditoria;
CREATE TRIGGER trg_auditoria_imutavel
BEFORE UPDATE OR DELETE ON seguranca.log_auditoria
FOR EACH ROW EXECUTE FUNCTION seguranca.proc_bloquear_mutacao();

DROP TRIGGER IF EXISTS trg_identidade_acesso_imutavel ON seguranca.identidade_acesso;
CREATE TRIGGER trg_identidade_acesso_imutavel
BEFORE UPDATE OR DELETE ON seguranca.identidade_acesso
FOR EACH ROW EXECUTE FUNCTION seguranca.proc_bloquear_mutacao();

-- 3. Revoga permissões de nível de banco do usuário atual dinamicamente
DO $$
DECLARE
    usuario_atual text;
BEGIN
    -- Captura o usuário que está rodando o script
    SELECT current_user INTO usuario_atual;

    -- Monta e executa o comando REVOKE dinamicamente
    EXECUTE format('REVOKE UPDATE, DELETE ON seguranca.log_auditoria FROM %I', usuario_atual);
    EXECUTE format('REVOKE UPDATE, DELETE ON seguranca.identidade_acesso FROM %I', usuario_atual);
    -- Apenas como boa prática, emite um aviso no console do log da migração
    RAISE NOTICE 'Permissões de UPDATE e DELETE revogadas de tabelas para o usuário: %', usuario_atual;
END $$;
