# Configurações de Log

# Banco de dados
db=postgres

# HTTP
http-enabled=true
http-relative-path=/

# Proxy
proxy-headers=xforwarded

# Observabilidade
health-enabled=true
metrics-enabled=true

# Log
log=console,file
log-file=/opt/keycloak/logs/keycloak.log
log-level=INFO
